Importing the libraries for reading the dataset and necessary manupulation.

In [1]:
import pandas as pd
import numpy as np

Loading the raw dataset file 1

In [2]:
df = pd.read_csv('../data/SIMD_2020_Data.csv')
df

,id,geom,datazone,intermedia,council_ar,total_popu,working_ag,simd2020v2,simd_2020v,simd2020_1,...,drive_petr,drive_gp,drive_post,drive_prim,drive_reta,drive_seco,pt_gp,pt_post,pt_retail,broadband
0,2207,0106000020E61000000100000001030000000100000061...,S01008712,"Bingham, Magdalene and The Christians",City of Edinburgh,1124.0,615.0,90.0,2.0,1.0,...,3.848445,1.804226,2.864838,3.856566,4.683930,4.300235,4.086367,7.022797,9.600905512,0.00
1,2198,0106000020E61000000100000001030000000100000032...,S01008703,Craigmillar,City of Edinburgh,1128.0,738.0,462.0,7.0,2.0,...,4.716391,3.012070,5.068158,2.657618,2.265327,4.882096,5.706106,8.562497,5.172350823,0.00
2,2202,0106000020E610000001000000010300000001000000A9...,S01008707,Niddrie,City of Edinburgh,953.0,616.0,173.0,3.0,1.0,...,5.908976,2.370157,2.089455,3.284226,3.397390,3.429833,6.155957,6.755342,7.094846288,0.00
3,2203,0106000020E6100000010000000103000000010000008F...,S01008708,Niddrie,City of Edinburgh,1043.0,649.0,164.0,3.0,1.0,...,6.281557,2.589499,2.563769,3.363543,3.596589,3.324262,5.535684,6.211121,6.542594289,0.02
4,6801,0106000020E6100000010000000103000000010000004A...,S01013306,Craigshill,West Lothian,1044.0,738.0,278.0,4.0,1.0,...,3.240983,2.215408,3.116243,2.509684,2.345567,5.364662,9.955902,12.170924,13.64662728,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,6745,0106000020E61000000300000001030000000100000049...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,45C6D21133E44B40364DD1FBF6F00DC0C2FACC9A35E44B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,6784,0106000020E6100000010000000103000000010000000B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Checking Id 
1) Filling null values with 0
2) Filtering Ids with length more than 5

In [3]:
df['id']=df['id'].fillna(value=0)
df['length_more_than_5'] = df['id'].apply(lambda x: len(str(x)) > 5)
df

,id,geom,datazone,intermedia,council_ar,total_popu,working_ag,simd2020v2,simd_2020v,simd2020_1,...,drive_gp,drive_post,drive_prim,drive_reta,drive_seco,pt_gp,pt_post,pt_retail,broadband,length_more_than_5
0,2207,0106000020E61000000100000001030000000100000061...,S01008712,"Bingham, Magdalene and The Christians",City of Edinburgh,1124.0,615.0,90.0,2.0,1.0,...,1.804226,2.864838,3.856566,4.683930,4.300235,4.086367,7.022797,9.600905512,0.00,False
1,2198,0106000020E61000000100000001030000000100000032...,S01008703,Craigmillar,City of Edinburgh,1128.0,738.0,462.0,7.0,2.0,...,3.012070,5.068158,2.657618,2.265327,4.882096,5.706106,8.562497,5.172350823,0.00,False
2,2202,0106000020E610000001000000010300000001000000A9...,S01008707,Niddrie,City of Edinburgh,953.0,616.0,173.0,3.0,1.0,...,2.370157,2.089455,3.284226,3.397390,3.429833,6.155957,6.755342,7.094846288,0.00,False
3,2203,0106000020E6100000010000000103000000010000008F...,S01008708,Niddrie,City of Edinburgh,1043.0,649.0,164.0,3.0,1.0,...,2.589499,2.563769,3.363543,3.596589,3.324262,5.535684,6.211121,6.542594289,0.02,False
4,6801,0106000020E6100000010000000103000000010000004A...,S01013306,Craigshill,West Lothian,1044.0,738.0,278.0,4.0,1.0,...,2.215408,3.116243,2.509684,2.345567,5.364662,9.955902,12.170924,13.64662728,0.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,6745,0106000020E61000000300000001030000000100000049...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1116,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1117,45C6D21133E44B40364DD1FBF6F00DC0C2FACC9A35E44B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1118,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1119,6784,0106000020E6100000010000000103000000010000000B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

Storing the indeices of the improper values observed in the dataset

In [4]:
indices = df[df['length_more_than_5']].index

# Shift data one column to the right for rows where 'length_more_than_5' is True
for index in indices:
    df.iloc[index, 1:] = df.iloc[index, :-1]

missing_data_rows = df[df['id'].str.len() > 5]
missing_data_rows

C:\Users\akars\AppData\Local\Temp\ipykernel_23400\2009445126.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '800' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[index, 1:] = df.iloc[index, :-1]
C:\Users\akars\AppData\Local\Temp\ipykernel_23400\2009445126.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '61' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[index, 1:] = df.iloc[index, :-1]
C:\Users\akars\AppData\Local\Temp\ipykernel_23400\2009445126.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '85%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[index, 1:] = df.iloc[index, :-1]
C:\Users\akars\AppData\Local\Temp\ipykernel_23400\2009445126.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.iloc[index, 1:] = df.iloc[index, :-1]

,id,geom,datazone,intermedia,council_ar,total_popu,working_ag,simd2020v2,simd_2020v,simd2020_1,...,drive_gp,drive_post,drive_prim,drive_reta,drive_seco,pt_gp,pt_post,pt_retail,broadband,length_more_than_5
1062,1C3EE82907C0D815EE9CEDED4B4029BAA1E1872907C0AC...,1C3EE82907C0D815EE9CEDED4B4029BAA1E1872907C0AC...,S01008247,IZ14,East Lothian,800,549.0,4307.0,62.0,13.0,...,10.453074,4.535079,2.371094,12.006420,12.476594,25.864110,12.526960,29.547709,85%,NaN
1063,84E53EA904C0EE17323BFBEB4B402E24879245A904C0D4...,84E53EA904C0EE17323BFBEB4B402E24879245A904C0D4...,S01008249,IZ14,East Lothian,907,538.0,3864.0,56.0,12.0,...,10.013801,4.883012,6.399167,10.079784,12.283606,23.270671,12.671427,23.113703,61%,NaN
1067,6B0CF71E0AC0F88817B4A3E34B40F519A367061F0AC0F2...,6B0CF71E0AC0F88817B4A3E34B40F519A367061F0AC0F2...,S01010930,Rural South Midlothian,Midlothian,939,602.0,5436.0,78.0,16.0,...,5.608419,5.554928,6.663140,6.894156,6.970294,20.187064,18.475753,21.578347,69%,NaN
1068,4B40FD072028AAE208C0530E9C68C3E24B409D0167F3B2...,4B40FD072028AAE208C0530E9C68C3E24B409D0167F3B2...,S01010931,Rural South Midlothian,Midlothian,890,583.0,4922.0,71.0,15.0,...,9.477988,8.492012,7.938114,8.797192,13.958186,23.694971,21.230029,21.99298,24%,NaN
1070,EF7267C606C0C2D16CDAFCE84B40EB4EFE5A69C606C0B9...,EF7267C606C0C2D16CDAFCE84B40EB4EFE5A69C606C0B9...,S01011019,Pathhead and Rural East Midlothian,Midlothian,1463,957.0,4076.0,59.0,12.0,...,3.620041,3.428257,5.572997,7.934185,9.467375,15.557173,14.045070,21.812822,36%,NaN
1071,C060A9641430F24B40DFD795CF03D50EC08609295530F2...,C060A9641430F24B40DFD795CF03D50EC08609295530F2...,S01011682,Caldercruix and Plains,North Lanarkshire,621,391.0,1092.0,16.0,4.0,...,6.699213,3.547328,4.466480,10.234995,8.528704,15.660335,8.050017,23.955942,44%,NaN
1072,1A7EC6E04B4074B092E1C6EA0AC04DD2A6D8B6E04B409C...,1A7EC6E04B4074B092E1C6EA0AC04DD2A6D8B6E04B409C...,S01012244,Tweeddale West Area,Scottish Borders,1002,661.0,4146.0,60.0,12.0,...,5.852937,5.799685,5.062285,14.870596,13.915877,14.375230,13.947981,32.796012,43%,NaN
1073,339F54CC09C0402C3D32B4E44B402B116A2B34CC09C03B...,339F54CC09C0402C3D32B4E44B402B116A2B34CC09C03B...,S01012247,Tweeddale West Area,Scottish Borders,852,510.0,4480.0,65.0,13.0,...,10.365404,9.556085,5.307526,11.020647,13.143111,25.499255,20.005448,24.177791,49%,NaN
1074,24771A4608C06005E200A3E34B406AF30F6CAC4308C0E1...,24771A4608C06005E200A3E34B406AF30F6CAC4308C0E1...,S01012271,Earlston Stow and Clovernfords Area,Scottish Borders,1643,1063.0,3750.0,54.0,11.0,...,11.255816,9.133622,8.418143,14.293321,17.179487,30.009534,25.663561,37.352799,46%,NaN
1075,28F16EBB06C05153800AABE84B40EB9E65071BBB06C007...,28F16EBB06C05153800AABE84B40EB9E65071BBB06C007...,S01012299,Lauder and Area,Scottish Borders,628,413.0,4599.0,66.0,14.0,...,9.719960,9.001695,5.393705,24.129287,21.317269,19.819658,16.810598,43.485201,46%,NaN
1076,FB9137370BC0DB8C074E84DB4B4023055387AF360BC0DB...,FB9137370BC0DB8C074E84DB4B4023055387AF360BC0DB...,S01012580,"Biggar, Symington, Thankerton and Dolphinton",South Lanarkshire,774,520.0,4157.0,60.0,12.0,...,8.671514,8.419309,5.415000,10.364014,11.489926,19.448972,18.760134,20.912024,62%,NaN
1077,C2B5C5D25F890CC0D481D10CE4E74B404B8CB3D063890C...,C2B5C5D25F890CC0D481D10CE4E74B404B8CB3D063890C...,S01013250,Breich Valley,West Lothian,884,588.0,3691.0,53.0,11.0,...,5.859971,5.151502,3.830935,6.367815,9.670987,15.379442,14.697280,15.961565,48%,NaN
1078,E050D5480BC05E0A056834E84B4011560929124A0BC0F4...,E050D5480BC05E0A056834E84B4011560929124A0BC0F4...,S01013289,Mid Calder and Kirknewton,West Lothian,1006,622.0,5728.0,83.0,17.0,...,7.267310,4.484446,3.970692,9.927533,9.611267,18.501987,10.950988,27.902877,39%,NaN
1087,4B40358BE864B75508C0A5D380933AE34B405DBE78DB3D...,4B40358BE864B75508C0A5D380933AE34B405DBE78DB3D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1089,3288C4ED4B40C2518D4D3A8C08C0A6039537B5ED4B407D...,3288C4ED4B40C2518D4D3A8C08C0A6039537B5ED4B407D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1091,BF92EB0309C042F249F693E14B40C12FC481E60309C008...,BF92EB0309C042F249F693E14B40C12FC481E60309C008...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1097,D4D4F04B40BBB21C299D5A0FC0DFBDCC63CEF04B40B1DE...,D4D4F04B40BBB21C299D5A0FC0DFBDCC63CEF04B40B1DE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099,40C802AD363EF20EC059664E85FBF14B40868EA72958F2...,40C802AD363EF20EC059664E85FBF14B40868EA72958F2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1101,D90EF14B40876641F994D10EC09C5C9ED40EF14B4098AA...,D90EF14B40876641F994D10EC09C5C9ED40EF14B4098AA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1105,830DFC8C0BC0A63A57EC37DE4B40D44D2DFB2E8D0BC09D...,830DFC8C0BC0A63A57EC37DE4B40D44D2DFB2E8D0BC09D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,45C6D21133E44B40364DD1FBF6F00DC0C2FACC9A35E44B...,45C6D21133E44B40364DD1FBF6F00DC0C2FACC9A35E44B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Producing a Dataframe with filtered values

In [5]:
cleaned_df=df[df['id'].str.len() <= 5]
cleaned_df

,id,geom,datazone,intermedia,council_ar,total_popu,working_ag,simd2020v2,simd_2020v,simd2020_1,...,drive_gp,drive_post,drive_prim,drive_reta,drive_seco,pt_gp,pt_post,pt_retail,broadband,length_more_than_5
0,2207,0106000020E61000000100000001030000000100000061...,S01008712,"Bingham, Magdalene and The Christians",City of Edinburgh,1124.0,615.0,90.0,2.0,1.0,...,1.804226,2.864838,3.856566,4.683930,4.300235,4.086367,7.022797,9.600905512,0.0,False
1,2198,0106000020E61000000100000001030000000100000032...,S01008703,Craigmillar,City of Edinburgh,1128.0,738.0,462.0,7.0,2.0,...,3.012070,5.068158,2.657618,2.265327,4.882096,5.706106,8.562497,5.172350823,0.0,False
2,2202,0106000020E610000001000000010300000001000000A9...,S01008707,Niddrie,City of Edinburgh,953.0,616.0,173.0,3.0,1.0,...,2.370157,2.089455,3.284226,3.397390,3.429833,6.155957,6.755342,7.094846288,0.0,False
3,2203,0106000020E6100000010000000103000000010000008F...,S01008708,Niddrie,City of Edinburgh,1043.0,649.0,164.0,3.0,1.0,...,2.589499,2.563769,3.363543,3.596589,3.324262,5.535684,6.211121,6.542594289,0.02,False
4,6801,0106000020E6100000010000000103000000010000004A...,S01013306,Craigshill,West Lothian,1044.0,738.0,278.0,4.0,1.0,...,2.215408,3.116243,2.509684,2.345567,5.364662,9.955902,12.170924,13.64662728,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109,5766,0106000020E6100000010000000103000000020000009B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1111,5794,0106000020E610000001000000010300000001000000FA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1113,6075,0106000020E61000000100000001030000000100000042...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1115,6745,0106000020E61000000300000001030000000100000049...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1119,6784,0106000020E6100000010000000103000000010000000B...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

Storing it to the processed dataset folder

In [6]:
csv_file_path = '../data/processed_data/cleaned_2020.csv'
# Writing the DataFrame to the Excel file
#cleaned_df.to_excel(excel_file_path, index=False)
cleaned_df.to_csv(csv_file_path,index=False)

Adding 2016 dataset too to make final combined file.

In [7]:
df_2016=pd.read_excel('../data/SIMD_2016_Data.xlsx')
df_2020=cleaned_df

Dropping unnecessary columns from SIMD 2020 dataframe

In [8]:
df_2020=df_2020.drop(columns=['id','geom','simd2020v2','simd_2020v','simd2020_1','simd2020_2','simd2020_3','simd2020_4','simd2020_e','simd2020_h','simd2020_5','simd2020_a','simd2020_c','simd2020_6','broadband','length_more_than_5'])

Creating Data Dictionary for mapping header names

In [9]:
header_map = {

    'datazone':'Data_Zone',
    'intermedia':'Intermediate_Zone',
    'council_ar':'Council_area',
    'total_popu':'Total_population',
    'working_ag':'Working_age_population_revised',
    'income_rat':'Income_rate',
    'income_cou':'Income_count',
    'employment':'Employment_rate',
    'employme_1':'Employment_count',
    'cif':'CIF',
    'alcohol':'ALCOHOL',
    'drug':'DRUG',
    'smr':'SMR',
    'depress':'DEPRESS',
    'lbwt':'LBWT',
    'emerg':'EMERG',
    'attendance':'Attendance',
    'attainment':'Attainment',
    'no_qualifi':'Noquals',
    'not_partic':'NEET',
    'university':'HESA',
    'drive_petr':'drive_petrol',
    'drive_gp':'drive_GP',
    'drive_post':'drive_PO',
    'drive_prim':'drive_primary',
    'drive_reta':'drive_retail',
    'drive_seco':'drive_secondary',
    'pt_gp':'PT_GP',
    'pt_post':'PT_Post',
    'pt_retail':'PT_retail',
    'crime_coun':'crime_count',
    'crime_rate':'crime_rate',
    'overcrowde':'overcrowded_count',
    'nocentralh':'nocentralheat_count',
    'overcrow_1':'overcrowded_rate',
    'nocentra_1':'nocentralheat_rate'
  }

Renaming headers in SIMD 2020 dataframe

In [11]:
df_2020 = df_2020.rename(columns=header_map)
df_2020

,Data_Zone,Intermediate_Zone,Council_area,Total_population,Working_age_population_revised,Income_rate,Income_count,Employment_rate,Employment_count,CIF,...,nocentralheat_rate,drive_petrol,drive_GP,drive_PO,drive_primary,drive_retail,drive_secondary,PT_GP,PT_Post,PT_retail
0,S01008712,"Bingham, Magdalene and The Christians",City of Edinburgh,1124.0,615.0,0.36,405.0,0.32,197.0,220.0,...,0.01,3.848445,1.804226,2.864838,3.856566,4.683930,4.300235,4.086367,7.022797,9.600905512
1,S01008703,Craigmillar,City of Edinburgh,1128.0,738.0,0.34,386.0,0.20,144.0,210.0,...,0.02,4.716391,3.012070,5.068158,2.657618,2.265327,4.882096,5.706106,8.562497,5.172350823
2,S01008707,Niddrie,City of Edinburgh,953.0,616.0,0.40,379.0,0.25,155.0,270.0,...,0.01,5.908976,2.370157,2.089455,3.284226,3.397390,3.429833,6.155957,6.755342,7.094846288
3,S01008708,Niddrie,City of Edinburgh,1043.0,649.0,0.34,359.0,0.28,183.0,225.0,...,0.05,6.281557,2.589499,2.563769,3.363543,3.596589,3.324262,5.535684,6.211121,6.542594289
4,S01013306,Craigshill,West Lothian,1044.0,738.0,0.31,326.0,0.23,170.0,230.0,...,0.03,3.240983,2.215408,3.116243,2.509684,2.345567,5.364662,9.955902,12.170924,13.64662728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Adding column "year" in both 2016 and 2020 dataframe

In [12]:
df_2016['year'] = 2016
df_2016['year'] = df_2016['year'].astype('int')
df_2020['year'] = 2020
df_2020['year'] = df_2020['year'].astype('int')

Combining both dataframes

In [13]:
combined_df = pd.concat([df_2016, df_2020], ignore_index=True)
combined_df

,Data_Zone,Intermediate_Zone,Council_area,Total_population,Working_age_population_revised,Income_rate,Income_count,Employment_rate,Employment_count,CIF,...,PT_GP,PT_Post,PT_retail,crime_count,crime_rate,overcrowded_count,nocentralheat_count,overcrowded_rate,nocentralheat_rate,year
0,S01006506,Culter,Aberdeen City,904,605.0,0.07,60.0,0.07,40.0,60,...,8.437832,5.987087,5.711433,8.006429,88.566697,87,10.0,0.102113,0.011737,2016
1,S01006507,Culter,Aberdeen City,830,491.0,0.07,60.0,0.05,25.0,40,...,8.331833,7.262817,6.7943,4.003215,48.231502,85,4.0,0.101675,0.004785,2016
2,S01006508,Culter,Aberdeen City,694,519.0,0.05,30.0,0.03,15.0,45,...,7.853631,5.827924,5.251454,4.003215,57.683209,31,8.0,0.048212,0.012442,2016
3,S01006509,Culter,Aberdeen City,573,354.0,0.05,30.0,0.06,20.0,65,...,7.434491,8.311862,8.444698,*,*,42,6.0,0.072414,0.010345,2016
4,S01006510,Culter,Aberdeen City,676,414.0,0.10,70.0,0.07,30.0,75,...,5.141013,6.627376,6.61913,12.009644,177.657457,50,7.0,0.086655,0.012132,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020

Exporting the combined dataframe to csv file

In [14]:
combined_df.to_csv('../data/processed_data/combined_dataset.csv', index=False, header=True)