In [ ]:
import pandas as pd

SIMD 2016 Data

In [ ]:
df_2016=pd.read_excel('../data/SIMD_2016_Data.xlsx')

SIMD 2020 Data

In [ ]:
df_2020=pd.read_excel('../data/cleaned_2020.xlsx')

Dropping unnecessary columns from SIMD 2020 dataframe

In [ ]:
df_2020=df_2020.drop(columns=['id','geom','simd2020v2','simd_2020v','simd2020_1','simd2020_2','simd2020_3','simd2020_4','simd2020_e','simd2020_h','simd2020_5','simd2020_a','simd2020_c','simd2020_6','broadband','length_more_than_5'])

Creating Data Dictionary for mapping header names

In [ ]:
header_map = {

    'datazone':'Data_Zone',
    'intermedia':'Intermediate_Zone',
    'council_ar':'Council_area',
    'total_popu':'Total_population',
    'working_ag':'Working_age_population_revised',
    'income_rat':'Income_rate',
    'income_cou':'Income_count',
    'employment':'Employment_rate',
    'employme_1':'Employment_count',
    'cif':'CIF',
    'alcohol':'ALCOHOL',
    'drug':'DRUG',
    'smr':'SMR',
    'depress':'DEPRESS',
    'lbwt':'LBWT',
    'emerg':'EMERG',
    'attendance':'Attendance',
    'attainment':'Attainment',
    'no_qualifi':'Noquals',
    'not_partic':'NEET',
    'university':'HESA',
    'drive_petr':'drive_petrol',
    'drive_gp':'drive_GP',
    'drive_post':'drive_PO',
    'drive_prim':'drive_primary',
    'drive_reta':'drive_retail',
    'drive_seco':'drive_secondary',
    'pt_gp':'PT_GP',
    'pt_post':'PT_Post',
    'pt_retail':'PT_retail',
    'crime_coun':'crime_count',
    'crime_rate':'crime_rate',
    'overcrowde':'overcrowded_count',
    'nocentralh':'nocentralheat_count',
    'overcrow_1':'overcrowded_rate',
    'nocentra_1':'nocentralheat_rate'
  }

Renaming headers in SIMD 2020 dataframe

In [ ]:
df_2020 = df_2020.rename(columns=header_map)

In [ ]:
df_2020

,Data_Zone,Intermediate_Zone,Council_area,Total_population,Working_age_population_revised,Income_rate,Income_count,Employment_rate,Employment_count,CIF,...,nocentralheat_rate,drive_petrol,drive_GP,drive_PO,drive_primary,drive_retail,drive_secondary,PT_GP,PT_Post,PT_retail
0,S01008712,"Bingham, Magdalene and The Christians",City of Edinburgh,1124.0,615.0,0.36,405.0,0.32,197.0,220.0,...,0.01,3.848445,1.804226,2.864838,3.856566,4.683930,4.300235,4.086367,7.022797,9.600906
1,S01008703,Craigmillar,City of Edinburgh,1128.0,738.0,0.34,386.0,0.20,144.0,210.0,...,0.02,4.716391,3.012070,5.068158,2.657618,2.265327,4.882096,5.706106,8.562497,5.172351
2,S01008707,Niddrie,City of Edinburgh,953.0,616.0,0.40,379.0,0.25,155.0,270.0,...,0.01,5.908976,2.370157,2.089455,3.284226,3.397390,3.429833,6.155957,6.755342,7.094846
3,S01008708,Niddrie,City of Edinburgh,1043.0,649.0,0.34,359.0,0.28,183.0,225.0,...,0.05,6.281557,2.589499,2.563769,3.363543,3.596589,3.324262,5.535684,6.211121,6.542594
4,S01013306,Craigshill,West Lothian,1044.0,738.0,0.31,326.0,0.23,170.0,230.0,...,0.03,3.240983,2.215408,3.116243,2.509684,2.345567,5.364662,9.955902,12.170924,13.646627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Adding column "year" in both 2016 and 2020 dataframe

In [ ]:
df_2016['year'] = 2016
df_2016['year'] = df_2016['year'].astype('int')

In [ ]:
df_2020['year'] = 2020
df_2020['year'] = df_2020['year'].astype('int')

Combining both dataframes

In [ ]:
combined_df = pd.concat([df_2016, df_2020], ignore_index=True)

In [ ]:
combined_df

,Data_Zone,Intermediate_Zone,Council_area,Total_population,Working_age_population_revised,Income_rate,Income_count,Employment_rate,Employment_count,CIF,...,PT_GP,PT_Post,PT_retail,crime_count,crime_rate,overcrowded_count,nocentralheat_count,overcrowded_rate,nocentralheat_rate,year
0,S01006506,Culter,Aberdeen City,904.0,605.0,0.07,60.0,0.07,40.0,60,...,8.437832,5.987087,5.711433,8.006429,88.566697,87.0,10.0,0.102113,0.011737,2016
1,S01006507,Culter,Aberdeen City,830.0,491.0,0.07,60.0,0.05,25.0,40,...,8.331833,7.262817,6.794300,4.003215,48.231502,85.0,4.0,0.101675,0.004785,2016
2,S01006508,Culter,Aberdeen City,694.0,519.0,0.05,30.0,0.03,15.0,45,...,7.853631,5.827924,5.251454,4.003215,57.683209,31.0,8.0,0.048212,0.012442,2016
3,S01006509,Culter,Aberdeen City,573.0,354.0,0.05,30.0,0.06,20.0,65,...,7.434491,8.311862,8.444698,*,*,42.0,6.0,0.072414,0.010345,2016
4,S01006510,Culter,Aberdeen City,676.0,414.0,0.10,70.0,0.07,30.0,75,...,5.141013,6.627376,6.619130,12.009644,177.657457,50.0,7.0,0.086655,0.012132,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020

Exporting the combined dataframe to csv file

In [ ]:
combined_df.to_csv('../data/combined_dataset.csv', index=False, header=True)